# Generated by Django 2.1.1 on 2019-07-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_auto_20190725_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_resume',
            field=models.TextField(blank=True, null=True, verbose_name='商品简述'),
        ),
    ]
